# Generated by Django 3.1.1 on 2020-09-16 08:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20200916_1112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-post_date']},
        ),
        migrations.AlterModelOptions(
            name='blogger',
            options={'ordering': ['user', 'bio']},
        ),
        migrations.RemoveField(
            model_name='blogger',
            name='username',
        ),
        migrations.AddField(
            model_name='blog',
            name='post_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='blogger',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='bio',
            field=models.TextField(help_text='Enter your bio details here.', max_length=400),
        ),
    ]
